{% set version = "2.12.0" %}

package:
  name: pylint
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pylint/pylint-{{ version }}.tar.gz
  sha256: 245c87e5da54c35b623c21b35debf87d93b18bf9e0229515cc172d0b83d627cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - pylint = pylint:run_pylint
    - epylint = pylint:run_epylint
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar

requirements:
  host:
    - python >=3.6,<4
    - pip

  run:
    - astroid >=2.8.0,<2.9
    - colorama
    - isort >=4.2.5,<6
    - mccabe >=0.6,<0.7
    - platformdirs >=2.2.0
    - python >=3.6,<4
    - toml >=0.7.1
    - typing_extensions

test:
  imports:
    - pylint
    - pylint.checkers
    - pylint.extensions
    - pylint.pyreverse
    - pylint.reporters
    - pylint.reporters.ureports

  commands:
    - pip check
    - pylint --help
    # Has no help option.
    # Running without arguments is an error.
    # So just check that it exists.
    - type epylint  # [unix]
    - where epylint  # [win]
    - pyreverse --help
    - symilar --help

  requires:
    - pip

about:
  home: https://www.pylint.org
  license: GPL-2.0-only
  license_file: LICENSE
  summary: python code static checker
  description: |
    Pylint is a tool that checks for errors in Python code, tries to enforce a
    coding standard and looks for code smells.
  doc_url: https://pylint.readthedocs.io
  doc_source_url: https://github.com/PyCQA/pylint/blob/v{{ version }}/doc
  dev_url: https://github.com/PyCQA/pylint

extra:
  recipe-maintainers:
    - jakirkham
    - timleslie
    - goanpeca
    - bollwyvl
    - wshanks
