{% set version = "2.14.1" %}
{% set min_astroid = "2.11.5" %}
{% set max_astroid = "2.12.0" %}

package:
  name: pylint
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pylint/pylint-{{ version }}.tar.gz
  sha256: 549261e0762c3466cc001024c4419c08252cb8c8d40f5c2c6966fea690e7fe2a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - pylint = pylint:run_pylint
    - epylint = pylint:run_epylint
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar

requirements:
  host:
    - python >=3.6.2,<4
    - pip

  run:
    - astroid >={{ min_astroid }},<{{ max_astroid }}
    - colorama
    - dill >=0.2
    - isort >=4.2.5,<6
    - mccabe >=0.6,<0.8
    - platformdirs >=2.2.0
    - python >=3.7.2
    - tomli >=1.1.0
    - tomlkit >=0.10.1
    - typing_extensions >=3.10.0

test:
  imports:
    - pylint
    - pylint.checkers
    - pylint.extensions
    - pylint.pyreverse
    - pylint.reporters
    - pylint.reporters.ureports

  commands:
    - pip check
    - pylint --help
    # Has no help option.
    # Running without arguments is an error.
    # So just check that it exists.
    - type epylint  # [unix]
    - where epylint  # [win]
    - pyreverse --help
    - symilar --help

  requires:
    - pip
    - astroid {{ min_astroid }}

about:
  home: https://pylint.org
  license: GPL-2.0-only
  license_file: LICENSE
  summary: python code static checker
  description: |
    Pylint is a tool that checks for errors in Python code, tries to enforce a
    coding standard and looks for code smells.
  doc_url: https://pylint.readthedocs.io
  doc_source_url: https://github.com/PyCQA/pylint/blob/v{{ version }}/doc
  dev_url: https://github.com/PyCQA/pylint

extra:
  recipe-maintainers:
    - jakirkham
    - timleslie
    - goanpeca
    - bollwyvl
    - wshanks
