{% set name = "pylint" %}
{% set version = "2.1.1" %}
{% set sha256 = "31142f764d2a7cd41df5196f9933b12b7ee55e73ef12204b648ad7e556c119fb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - pylint = pylint:run_pylint
    - epylint = pylint:run_epylint
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar

requirements:
  build:
    - python
    - pip
    - pytest-runner

  run:
    - python
    - astroid >=1.6,<2.0
    - backports.functools_lru_cache  # [py27]
    - configparser                   # [py27]
    - singledispatch                 # [py27]
    - colorama                       # [win]
    - six
    - isort >=4.2.5
    - mccabe

test:
  imports:
    - pylint
    - pylint.checkers
    - pylint.extensions
    - pylint.pyreverse
    - pylint.reporters
    - pylint.reporters.ureports

  commands:
    - pylint --help
    # Has no help option.
    # Running without arguments is an error.
    # So just check that it exists.
    - which epylint     # [unix]
    - where epylint     # [win]
    - pyreverse --help
    - symilar --help

about:
  home: https://github.com/PyCQA/pylint
  license: GPL 2
  license_file: COPYING
  summary: 'python code static checker'

extra:
  recipe-maintainers:
    - jakirkham
    - timleslie
