{% set version = "3.3.3" %}
{% set min_astroid = "3.3.8" %}
{% set max_astroid = "3.4.0-dev0" %}

package:
  name: pylint
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pylint/pylint-{{ version }}.tar.gz
  sha256: 07c607523b17e6d16e2ae0d7ef59602e332caa762af64203c24b41c27139f36a

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - pylint = pylint:run_pylint
    - pylint-config = pylint:_run_pylint_config
    - pyreverse = pylint:run_pyreverse
    - symilar = pylint:run_symilar

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=71.0.4

  run:
    - astroid >={{ min_astroid }},<{{ max_astroid }}
    - colorama >=0.4.5
    - isort >=4.2.5,<6,!=5.13.0
    - mccabe >=0.6,<0.8
    - platformdirs >=2.2.0
    - python >={{ python_min }}
    - tomli >=1.1.0
    - tomlkit >=0.10.1
    - typing_extensions >=3.10.0
    # technically...
    # "dill>=0.2;python_version<'3.11'",
    # "dill>=0.3.6;python_version>='3.11'",
    # "dill>=0.3.7;python_version>='3.12'",
    # but to keep noarch...
    - dill >=0.3.7

test:
  imports:
    - pylint
    - pylint.checkers
    - pylint.extensions
    - pylint.pyreverse
    - pylint.reporters
    - pylint.reporters.ureports

  commands:
    - pip check
    - pylint --help
    - pyreverse --help
    - symilar --help
    # currently exits 1 with some warnings about being experimental
    - which pylint-config || where pylint-config

  requires:
    - pip
    - python {{ python_min }}
    - astroid {{ min_astroid }}

about:
  home: https://github.com/pylint-dev/pylint
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: python code static checker
  description: |
    Pylint is a tool that checks for errors in Python code, tries to enforce a
    coding standard and looks for code smells.
  doc_url: https://pylint.readthedocs.io
  doc_source_url: https://github.com/pylint-dev/pylint/blob/v{{ version }}/doc

extra:
  recipe-maintainers:
    - timkpaine
    - jakirkham
    - timleslie
    - goanpeca
    - bollwyvl
    - wshanks
