# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.3.5"
  min_astroid: "3.3.8"
  max_astroid: "3.4.0-dev0"

package:
  name: pylint
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pylint/pylint-${{ version }}.tar.gz
  sha256: 38d0f784644ed493d91f76b5333a0e370a1c1bc97c22068a77523b4bf1e82c31

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - pylint = pylint:run_pylint
      - pylint-config = pylint:_run_pylint_config
      - pyreverse = pylint:run_pyreverse
      - symilar = pylint:run_symilar

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=71.0.4
  run:
    - astroid >=${{ min_astroid }},<${{ max_astroid }}
    - colorama >=0.4.5
    - isort >=4.2.5,<7,!=5.13.0
    - mccabe >=0.6,<0.8
    - platformdirs >=2.2.0
    - python >=${{ python_min }}
    - tomli >=1.1.0
    - tomlkit >=0.10.1
    - typing_extensions >=3.10.0
    # technically...
    # "dill>=0.2;python_version<'3.11'",
    # "dill>=0.3.6;python_version>='3.11'",
    # "dill>=0.3.7;python_version>='3.12'",
    # but to keep noarch...
    - dill >=0.3.7

tests:
  - python:
      python_version: ${{ python_min }}.*
      pip_check: true
      imports:
        - pylint
        - pylint.checkers
        - pylint.extensions
        - pylint.pyreverse
        - pylint.reporters
        - pylint.reporters.ureports
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
        - astroid ${{ min_astroid }}
    script:
      # repeat pip check to catch astroid, which cannot be constrained above
      - pip check
      - pylint --help
      - pyreverse --help
      - symilar --help
      - which pylint-config || where pylint-config

about:
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: python code static checker
  description: |
    Pylint is a tool that checks for errors in Python code, tries to enforce a
    coding standard and looks for code smells.
  homepage: https://github.com/pylint-dev/pylint
  documentation: https://pylint.readthedocs.io

extra:
  recipe-maintainers:
    - timkpaine
    - jakirkham
    - timleslie
    - goanpeca
    - bollwyvl
    - wshanks
