appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: VmhwRIyGOSsYglStakb3SMVl/DWe3EvMKHqpbgtpUJu6qDfM0fHzCeFnCs8u0hPMF/G6uYu6sv8Ca5kIKbp0kLNluGeJCQpHJTwb5+wUXIZhokxeVatRTVOCfxAFXypO8phcxp6B/r4iNIpYBHZB8Y1iVMLDuOOhT0ZDX0qubakRM8ism95CP6R7NPsSQU1hydAXvWxIqqAkISRuJovUZSZF7tCUCHuquxvkbmXShHIMOpxynyVVZA6FKHgLjdvhfyDkOLvKcMGlIXxOvPS3rg8kwqG2VsyjBGjtrHDtaitCueUAOjqKTxWsbpbBc9HdK1sZDiWlBl+zSaMja2+WKZXUkQbcIxiyoeBNnYJCGK+eg44FtIfu65aDXkVrRoB+CbYOXAjWIQceIuWdqbB5fbBNC/FWlSQxFD4haBIb9hOYjCab8HzPz5Kr+6MkL4vYPTNqEGSkvMbFg24zznjNjowhkrwa3jBDOPejZrVaLNrbXXc6GEx5aqErgjoHyZWaKImGksrkKSTTKN4n9rzueBN2O0CPaRGxbeNfNtACSzcgQ2J+YYKaSFogJQzgcpV567kugICN5CDNWbp3NMU1pWFkWJF64FK5jMJvDmJE9mdJIFp517Btc4GR+K636gVm16Cl2SiUoRLatLODRcA/f9tQKzyDGQ0lyjVSfR0uE0U=}
provider:
  win: azure
  linux_aarch64: azure
  